<a href="https://colab.research.google.com/github/Kwangbin/numpy/blob/main/numpy_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.arange(15,dtype=np.int64)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
x=np.arange(15,dtype=np.int64)

In [ ]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
x.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
x.shape

(15,)

In [ ]:
x.reshape(3,5).shape

(3, 5)

In [ ]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
x=x.reshape(3,5)

In [ ]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
x[:]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
x[:,:]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
x[1:,:]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
# ::2   
# start,stop, sterp  
# 즉, 처음 , 끝, 2간격
x[1:,::2]

array([[ 5,  7,  9],
       [10, 12, 14]])

In [ ]:
#값 변경
# 해당 되느 값 전부 99 변경
x[1:,::2]=99

In [ ]:
x

array([[ 0,  1,  2,  3,  4],
       [99,  6, 99,  8, 99],
       [99, 11, 99, 13, 99]])

In [ ]:
x[1:,::2]=-99

In [ ]:
x

array([[  0,   1,   2,   3,   4],
       [-99,   6, -99,   8, -99],
       [-99,  11, -99,  13, -99]])

In [ ]:
x.max()

13

In [ ]:
# 축지정
x.max(axis=1)

array([ 4,  8, 13])

In [ ]:
# 축지정
x.max(axis=0)

array([ 0, 11,  2, 13,  4])

In [ ]:
#w정규분포 만들기
np.random.default_rng()

Generator(PCG64) at 0x7F3CEA2257D0

In [ ]:
rng=np.random.default_rng()

In [ ]:
samples=rng.normal(size=2500)

In [ ]:
samples

array([-1.66513809, -1.29160781,  1.01769965, ...,  1.27112797,
        0.08951476, -2.93823121])

#Numpy Fast

In [ ]:
import numpy as np

In [ ]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
b= np.arange(5,10)
b

array([5, 6, 7, 8, 9])

In [ ]:
#[] 는 빈 list생성
c=[]
for i in range(len(a)):
    c.append(a[i]*b[i])

In [ ]:
c

[0, 6, 14, 24, 36]

In [ ]:
#간결한 파이썬 코드
c = a* b
c

array([ 0,  6, 14, 24, 36])

###속도측정

In [ ]:
%%timeit
c=[]
for i in range(len(a)):
    c.append(a[i]*b[i])

The slowest run took 12.81 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 2.12 µs per loop


In [ ]:
#반복분  계산 2.12 µs  즉 마이크로 세컨드

In [ ]:
%%timeit
c = a* b
c

The slowest run took 121.57 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 569 ns per loop


In [ ]:
#벡터 연산은 568 ns 나노세컨드
# 즉 벡터 연산이 쉽고 빠르다

##데이터 shape종류
0차원 : scalar (7)

1차원 : vector ([1,1])

2차원 : matrix([1,1],[2,2])

3차원 : 3-tensor([[[1,2,3],[4,5,6]] , [[7,8,9], [10,11,12]]])

n차원 : n-tensor

넘파이 차원 변경

In [ ]:
a= np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
a2=a[np.newaxis, :]
a2

array([[0, 1, 2, 3, 4, 5]])

In [ ]:
#차원을  확인하면 1차원, 2차원
a.shape, a2.shape

((6,), (1, 6))

###파이썬은 배열에 다양한 자료형을 포함 할수 있다
###그러난 넘파이는 배열에 동일 유형만 가능 하다

In [ ]:
a_list=[1,2,"3",4.]
a_list

[1, 2, '3', 4.0]

In [ ]:
type(a_list)

list

In [ ]:
#U32 문자형 타입
np.array(a_list)

array(['1', '2', '3', '4.0'], dtype='<U32')

In [ ]:
#배열
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

###배열의 차원은  1차원 [ ] 2차원[ [  ] ] 3차원 [ [ [ ] ] ]

In [ ]:
#배열의 접근은 번호 한다
a[0]

array([1, 2, 3, 4])